# Award Definitions Configuration
# Define all enabled award programs for the application

awards:
  - name: DXCC
    program_id: DXCC_MIXED
    type: entity_count
    enabled: true
    requirements:
      entity_count: 100
      confirmation: true
      modes:
        - MIXED
        - CW
        - PHONE
        - DIGITAL
      bands: null  # null = all bands
    endorsements:
      - level: 100
        description: "DXCC Certificate"
      - level: 150
        step: 50
        description: "50-entity endorsements"
      - level: 250
        step: 50
      - level: 300
        step: 25
    handler: dxcc.py

  - name: WAS
    program_id: WAS_MIXED
    type: entity_count
    enabled: true
    requirements:
      entity_count: 50
      entity_type: us_states
      confirmation: true
      modes:
        - MIXED
        - CW
        - PHONE
        - DIGITAL
    endorsements:
      - level: 50
        description: "WAS Certificate"
      - level: 75
        step: 25
    handler: was.py

  - name: WAC
    program_id: WAC_MIXED
    type: entity_count
    enabled: true
    requirements:
      entity_count: 6
      entity_type: continents
      confirmation: true
    endorsements:
      - level: 6
        description: "WAC Certificate"
    handler: wac.py

  - name: SKCC_Centurion
    program_id: SKCC_CEN
    type: unique_contact_count
    enabled: true
    requirements:
      unique_contacts: 100
      organization: SKCC
      mode: CW
      mechanical_key_required: true
    endorsements:
      - level: 100
        description: "Centurion Award"
      - level: 200
        description: "Centurion x2"
      - level: 1000
        description: "Centurion x10"
    handler: centurion.py

  - name: SKCC_Tribune
    program_id: SKCC_TRB
    type: unique_contact_count
    enabled: true
    requirements:
      unique_contacts: 50
      organization: SKCC
      mode: CW
      mechanical_key_required: true
      prerequisite: "SKCC_Centurion"
      effective_date: "20070301"
    endorsements:
      - level: 50
        description: "Tribune Award"
      - level: 100
        description: "Tribune x2"
      - level: 400
        description: "Tribune x8"
    handler: tribune.py

  - name: SKCC_Senator
    program_id: SKCC_SEN
    type: unique_contact_count
    enabled: true
    requirements:
      unique_contacts: 200
      organization: SKCC
      mode: CW
      mechanical_key_required: true
      prerequisite: "SKCC_Tribune"
      effective_date: "20130801"
      prerequisite_level: "Tribune x8"
    endorsements:
      - level: 200
        description: "Senator Award"
      - level: 400
        description: "Senator x2"
      - level: 2000
        description: "Senator x10"
    handler: senator.py

  - name: IOTA
    program_id: IOTA_MIXED
    type: entity_count
    enabled: false
    requirements:
      entity_type: iota_islands
    endorsements:
      - level: 100
        description: "IOTA Award"
    handler: iota.py

  - name: SOTA
    program_id: SOTA_MIXED
    type: entity_count
    enabled: false
    requirements:
      entity_type: sota_summits
    endorsements:
      - level: 100
        description: "SOTA Award"
    handler: sota.py
